modLoader = "javafml"
loaderVersion = "[40,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "emi"
version = "${version}"
displayName = "EMI"
authors = "Emi"
description = '''
A featureful and accessible item and recipe viewer
'''
logoFile = "icon.png"

[[dependencies.emi]]
modId = "jei"
mandatory = false
versionRange = "[15.20.0.0,)"
ordering = "BEFORE"
side = "CLIENT"